package gui;
import java.awt.*;

import javax.swing.*;


public class Playground extends JFrame					// JFrame Spielfenster
{
	int r;													// Integer r,g,b Variablen f¸r die Hintergrundfarbe des Fensters
	int g;
	int b;
	private JPanel jPanel1 = new JPanel(null, true);		// JPanels zum zeichen der Linien
	private JPanel jPanel2 = new JPanel(null, true);
	private JPanel jPanel3 = new JPanel(null, true);
	private JPanel jPanel4 = new JPanel(null, true);
	private JPanel jPanel5 = new JPanel(null, true);
	private JPanel jPanel6 = new JPanel(null, true);
	private JPanel jPanel7 = new JPanel(null, true);
	private JPanel jPanel8 = new JPanel(null, true);
	private JPanel jPanel9 = new JPanel(null, true);
	private JPanel jPanel10 = new JPanel(null, true);
	private JPanel jPanel11 = new JPanel(null, true);
	private JPanel jPanel12 = new JPanel(null, true);
	private Circles circleweiﬂ1 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ2 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ3 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ4 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ5 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ6 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ7 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ8 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ9 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ10 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ11 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ12 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ13 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ14 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ15 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ16 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ17 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ18 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ19 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ20 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ21 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ22 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ23 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ24 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ25 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ26 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ27 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ28 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ29 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ30 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ31 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ32 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ33 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ34 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ35 = new Circles(Color.WHITE,"","");
	private Circles circleweiﬂ36 = new Circles(Color.WHITE,"","");
	private Circles circleblau1 = new Circles(Color.BLUE,"","");
	private Circles circleblau2 = new Circles(Color.BLUE,"","");
	private Circles circleblau3 = new Circles(Color.BLUE,"","");
	private Circles circleblau4 = new Circles(Color.BLUE,"","");
	private Circles circleblau5 = new Circles(Color.BLUE,"","");
	private Circles circleblau6 = new Circles(Color.BLUE,"","a");
	private Circles circleblau7 = new Circles(Color.BLUE,"","b");
	private Circles circleblau8 = new Circles(Color.BLUE,"","c");
	private Circles circleblau9 = new Circles(Color.BLUE,"","d");
	private Circles circlegreen1 = new Circles(Color.GREEN,"","");
	private Circles circlegreen2 = new Circles(Color.GREEN,"","a");
	private Circles circlegreen3 = new Circles(Color.GREEN,"","b");
	private Circles circlegreen4 = new Circles(Color.GREEN,"","c");
	private Circles circlegreen5 = new Circles(Color.GREEN,"","d");
	private Circles circlegreen6 = new Circles(Color.GREEN,"","");
	private Circles circlegreen7 = new Circles(Color.GREEN,"","");
	private Circles circlegreen8 = new Circles(Color.GREEN,"","");
	private Circles circlegreen9 = new Circles(Color.GREEN,"","");
	private Circles circleyellow1 = new Circles(Color.YELLOW,"","a");
	private Circles circleyellow2 = new Circles(Color.YELLOW,"","b");
	private Circles circleyellow3 = new Circles(Color.YELLOW,"","c");
	private Circles circleyellow4 = new Circles(Color.YELLOW,"","d");
	private Circles circleyellow5 = new Circles(Color.YELLOW,"","");
	private Circles circleyellow6 = new Circles(Color.YELLOW,"","");
	private Circles circleyellow7 = new Circles(Color.YELLOW,"","");
	private Circles circleyellow8 = new Circles(Color.YELLOW,"","");
	private Circles circleyellow9 = new Circles(Color.YELLOW,"","");
	private Circles circlered1 = new Circles(Color.RED,"","");
	private Circles circlered2 = new Circles(Color.RED,"","");
	private Circles circlered3 = new Circles(Color.RED,"","");
	private Circles circlered4 = new Circles(Color.RED,"","");
	private Circles circlered5 = new Circles(Color.RED,"","");
	private Circles circlered6 = new Circles(Color.RED,"","a");
	private Circles circlered7 = new Circles(Color.RED,"","b");
	private Circles circlered8 = new Circles(Color.RED,"","c");
	private Circles circlered9 = new Circles(Color.RED,"","d");
	public JLabel textfield1 = new JLabel();
	public JLabel textfield2 = new JLabel();
	public JLabel textfield3 = new JLabel();
	public JLabel textfield4 = new JLabel();
	public static JTextArea jTextArea1 = new JTextArea();
	private JScrollPane jTextArea1ScrollPane = new JScrollPane(jTextArea1);
	public Circles redone = new Circles(Color.RED,"1","");
	public Circles redtwo = new Circles(Color.RED, "2","");
	public Circles redthree = new Circles(Color.RED, "3","");
	public Circles redfour = new Circles(Color.RED, "4","");
	public Circles blueone = new Circles(Color.BLUE,"1","");
	public Circles bluetwo = new Circles(Color.BLUE, "2","");
	public Circles bluethree = new Circles(Color.BLUE, "3","");
	public Circles bluefour = new Circles(Color.BLUE, "4","");
	public Circles greenone = new Circles(Color.GREEN,"1","");
	public Circles greentwo = new Circles(Color.GREEN, "2","");
	public Circles greenthree = new Circles(Color.GREEN, "3","");
	public Circles greenfour = new Circles(Color.GREEN, "4","");
	public Circles yellowone = new Circles(Color.YELLOW,"1","");
	public Circles yellowtwo = new Circles(Color.YELLOW, "2","");
	public Circles yellowthree = new Circles(Color.YELLOW, "3","");
	public Circles yellowfour = new Circles(Color.YELLOW, "4","");
//	private Arrow pfeilArrow = new Arrow();
	

	public Playground()
	{
		super();
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);		// Programm wird beim schlieﬂen des Fensters beendet
		int frameWidth = 1800;											// Grˆﬂe des Spielfensters
		int frameHeight = 1000;
		setSize(frameWidth, frameHeight);	
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();		// Fenster wird mittig ausgerichtet
		int x = (d.width - getSize().width) / 2;
		int y = (d.height - getSize().height) / 2;
		setLocation(x, y);
		setTitle("Mensch ‰rgere Dich Nicht");							// Titel des Fensters
		setResizable(false);											// Grˆﬂe nicht ver‰nderbar
		Container cp = getContentPane();								// Container f¸r Fenstervariablen
		cp.setLayout(null);
		cp.setBackground(new Color(r = 204, g = 164, b = 96));			// Hintergrundfarbe Fenster

//		pfeilArrow.setBounds(100, 200, 200, 500);
//		cp.add(pfeilArrow);
		yellowone.setBounds(10, 820, 61, 61);
		cp.add(yellowone);
		yellowtwo.setBounds(80, 820, 61, 61);
		cp.add(yellowtwo);
		yellowthree.setBounds(10, 890, 61, 61);
		cp.add(yellowthree);
		yellowfour.setBounds(80, 890, 61, 61);
		cp.add(yellowfour);
		greenone.setBounds(840, 820, 61, 61);
		cp.add(greenone);
		greentwo.setBounds(910, 820, 61, 61);
		cp.add(greentwo);
		greenthree.setBounds(840, 890, 61, 61);
		cp.add(greenthree);
		greenfour.setBounds(910, 890, 61, 61);
		cp.add(greenfour);
		blueone.setBounds(840, 10, 61, 61);
		cp.add(blueone);
		bluetwo.setBounds(910, 10, 61, 61);
		cp.add(bluetwo);
		bluethree.setBounds(840, 80, 61, 61);
		cp.add(bluethree);
		bluefour.setBounds(910, 80, 61, 61);
		cp.add(bluefour);
		redfour.setBounds(80, 80, 61, 61);
		cp.add(redfour);
		redthree.setBounds(10, 80, 61, 61);
		cp.add(redthree);
		redtwo.setBounds(80, 10, 61, 61);
		cp.add(redtwo);
		redone.setBounds(10, 10, 61, 61);
		cp.add(redone);
		jTextArea1ScrollPane.setBounds(980, 10, 795, 940);
		jTextArea1.setFont(new Font("Times New Roman", Font.BOLD, 20));
		cp.add(jTextArea1ScrollPane);
		textfield1.setBounds(30, 140, 100, 30);
//	    textfield1.setText(LoadGui.startScreen.playerNames.gameLogic.getPlayerOneNameString());
	    cp.add(textfield1); 
	    textfield2.setBounds(860, 140, 100, 30);
//	    textfield2.setText(LoadGui.startScreen.playerNames.gameLogic.getPlayerTwoNameString());
	    cp.add(textfield2);
	    textfield3.setBounds(30, 790, 100, 30);
//	    textfield3.setText(LoadGui.startScreen.playerNames.gameLogic.getPlayerThreeNameString());
	    cp.add(textfield3); 
	    textfield4.setBounds(860, 790, 100, 30);
//	    textfield4.setText(LoadGui.startScreen.playerNames.gameLogic.getPlayerFourNameString());
	    cp.add(textfield4);
		circleweiﬂ1.setBounds(380, 366, 61, 61);
		circleweiﬂ1.setOpaque(true);
		cp.add(circleweiﬂ1);
		circleweiﬂ2.setBounds(380, 284, 61, 61);
		circleweiﬂ2.setOpaque(true);
		cp.add(circleweiﬂ2);
		circleweiﬂ3.setBounds(380, 202, 61, 61);
		circleweiﬂ3.setOpaque(true);
		cp.add(circleweiﬂ3);
		circleweiﬂ4.setBounds(380, 120, 61, 61);
		circleweiﬂ4.setOpaque(true);
		cp.add(circleweiﬂ4);
		circleweiﬂ5.setBounds(380, 38, 61, 61);
		circleweiﬂ5.setOpaque(true);
		cp.add(circleweiﬂ5);
		circleweiﬂ6.setBounds(467, 38, 61, 61);
		circleweiﬂ6.setOpaque(true);
		cp.add(circleweiﬂ6);
		circleweiﬂ7.setBounds(555, 120, 61, 61);
		circleweiﬂ7.setOpaque(true);
		cp.add(circleweiﬂ7);
		circleweiﬂ8.setBounds(555, 202, 61, 61);
		circleweiﬂ8.setOpaque(true);
		cp.add(circleweiﬂ8);
		circleweiﬂ9.setBounds(555, 284, 61, 61);
		circleweiﬂ9.setOpaque(true);
		cp.add(circleweiﬂ9);
		circleweiﬂ10.setBounds(555, 366, 61, 61);
		circleweiﬂ10.setOpaque(true);
		cp.add(circleweiﬂ10);
		circleweiﬂ11.setBounds(642, 366, 61, 61);
		circleweiﬂ11.setOpaque(true);
		cp.add(circleweiﬂ11);
		circleweiﬂ12.setBounds(724, 366, 61, 61);
		circleweiﬂ12.setOpaque(true);
		cp.add(circleweiﬂ12);
		circleweiﬂ13.setBounds(806, 366, 61, 61);
		circleweiﬂ13.setOpaque(true);
		cp.add(circleweiﬂ13);
		circleweiﬂ14.setBounds(888, 366, 61, 61);
		circleweiﬂ14.setOpaque(true);
		cp.add(circleweiﬂ14);
		circleweiﬂ15.setBounds(888, 454, 61, 61);
		circleweiﬂ15.setOpaque(true);
		cp.add(circleweiﬂ15);
		circleweiﬂ16.setBounds(806, 542, 61, 61);
		circleweiﬂ16.setOpaque(true);
		cp.add(circleweiﬂ16);
		circleweiﬂ17.setBounds(724, 542, 61, 61);
		circleweiﬂ17.setOpaque(true);
		cp.add(circleweiﬂ17);
		circleweiﬂ18.setBounds(642, 542, 61, 61);
		circleweiﬂ18.setOpaque(true);
		cp.add(circleweiﬂ18);
		circleweiﬂ19.setBounds(555, 542, 61, 61);
		circleweiﬂ19.setOpaque(true);
		cp.add(circleweiﬂ19);
		circleweiﬂ20.setBounds(555, 624, 61, 61);
		circleweiﬂ20.setOpaque(true);
		cp.add(circleweiﬂ20);
		circleweiﬂ21.setBounds(555, 706, 61, 61);
		circleweiﬂ21.setOpaque(true);
		cp.add(circleweiﬂ21);
		circleweiﬂ22.setBounds(555, 788, 61, 61);
		circleweiﬂ22.setOpaque(true);
		cp.add(circleweiﬂ22);
		circleweiﬂ23.setBounds(555, 870, 61, 61);
		circleweiﬂ23.setOpaque(true);
		cp.add(circleweiﬂ23);
		circleweiﬂ24.setBounds(467, 870, 61, 61);
		circleweiﬂ24.setOpaque(true);
		cp.add(circleweiﬂ24);
		circleweiﬂ25.setBounds(380, 788, 61, 61);
		circleweiﬂ25.setOpaque(true);
		cp.add(circleweiﬂ25);
		circleweiﬂ26.setBounds(380, 706, 61, 61);
		circleweiﬂ26.setOpaque(true);
		cp.add(circleweiﬂ26);
		circleweiﬂ27.setBounds(380, 624, 61, 61);
		circleweiﬂ27.setOpaque(true);
		cp.add(circleweiﬂ27);
		circleweiﬂ28.setBounds(380, 542, 61, 61);
		circleweiﬂ28.setOpaque(true);
		cp.add(circleweiﬂ28);
		circleweiﬂ29.setBounds(293, 542, 61, 61);
		circleweiﬂ29.setOpaque(true);
		cp.add(circleweiﬂ29);
		circleweiﬂ30.setBounds(211, 542, 61, 61);
		circleweiﬂ30.setOpaque(true);
		cp.add(circleweiﬂ30);
		circleweiﬂ31.setBounds(126, 542, 61, 61);
		circleweiﬂ31.setOpaque(true);
		cp.add(circleweiﬂ31);
		circleweiﬂ32.setBounds(38, 542, 61, 61);
		circleweiﬂ32.setOpaque(true);
		cp.add(circleweiﬂ32);
		circleweiﬂ33.setBounds(38, 454, 61, 61);
		circleweiﬂ33.setOpaque(true);
		cp.add(circleweiﬂ33);
		circleweiﬂ34.setBounds(124, 366, 61, 61);
		circleweiﬂ34.setOpaque(true);
		cp.add(circleweiﬂ34);
		circleweiﬂ35.setBounds(208, 366, 61, 61);
		circleweiﬂ35.setOpaque(true);
		cp.add(circleweiﬂ35);
		circleweiﬂ36.setBounds(292, 366, 61, 61);
		circleweiﬂ36.setOpaque(true);
		cp.add(circleweiﬂ36);

		circlegreen1.setBounds(888, 542, 61, 61);
		circlegreen1.setOpaque(true);
		cp.add(circlegreen1);
		circlegreen2.setBounds(806, 454, 61, 61);
		circlegreen2.setOpaque(true);
		cp.add(circlegreen2);
		circlegreen3.setBounds(724, 454, 61, 61);
		circlegreen3.setOpaque(true);
		cp.add(circlegreen3);
		circlegreen4.setBounds(642, 454, 61, 61);
		circlegreen4.setOpaque(true);
		cp.add(circlegreen4);
		circlegreen5.setBounds(555, 454, 61, 61);
		circlegreen5.setOpaque(true);
		cp.add(circlegreen5);
		circlegreen6.setBounds(910, 890, 61, 61);
		circlegreen6.setOpaque(true);
		cp.add(circlegreen6);
		circlegreen7.setBounds(910, 820, 61, 61);
		circlegreen7.setOpaque(true);
		cp.add(circlegreen7);
		circlegreen8.setBounds(840, 820, 61, 61);
		circlegreen8.setOpaque(true);
		cp.add(circlegreen8);
		circlegreen9.setBounds(840, 890, 61, 61);
		circlegreen9.setOpaque(true);
		cp.add(circlegreen9);

		circleblau1.setBounds(555, 38, 61, 61);
		circleblau1.setOpaque(true);
		cp.add(circleblau1);
		circleblau2.setBounds(910, 10, 61, 61);
		circleblau2.setOpaque(true);
		cp.add(circleblau2);
		circleblau3.setBounds(840, 10, 61, 61);
		circleblau3.setOpaque(true);
		cp.add(circleblau3);
		circleblau4.setBounds(910, 80, 61, 61);
		circleblau4.setOpaque(true);
		cp.add(circleblau4);
		circleblau5.setBounds(840, 80, 61, 61);
		circleblau5.setOpaque(true);
		cp.add(circleblau5);
		circleblau6.setBounds(467, 120, 61, 61);
		circleblau6.setOpaque(true);
		cp.add(circleblau6);
		circleblau7.setBounds(467, 202, 61, 61);
		circleblau7.setOpaque(true);
		cp.add(circleblau7);
		circleblau8.setBounds(467, 284, 61, 61);
		circleblau8.setOpaque(true);
		cp.add(circleblau8);
		circleblau9.setBounds(467, 366, 61, 61);
		circleblau9.setOpaque(true);
		cp.add(circleblau9);

		circleyellow1.setBounds(467, 788, 61, 61);
		circleyellow1.setOpaque(true);
		cp.add(circleyellow1);
		circleyellow2.setBounds(467, 706, 61, 61);
		circleyellow2.setOpaque(true);
		cp.add(circleyellow2);
		circleyellow3.setBounds(467, 624, 61, 61);
		circleyellow3.setOpaque(true);
		cp.add(circleyellow3);
		circleyellow4.setBounds(467, 542, 61, 61);
		circleyellow4.setOpaque(true);
		cp.add(circleyellow4);
		circleyellow5.setBounds(380, 870, 61, 61);
		circleyellow5.setOpaque(true);
		cp.add(circleyellow5);
		circleyellow6.setBounds(80, 890, 61, 61);
		circleyellow6.setOpaque(true);
		cp.add(circleyellow6);
		circleyellow7.setBounds(10, 890, 61, 61);
		circleyellow7.setOpaque(true);
		cp.add(circleyellow7);
		circleyellow8.setBounds(10, 820, 61, 61);
		circleyellow8.setOpaque(true);
		cp.add(circleyellow8);
		circleyellow9.setBounds(80, 820, 61, 61);
		circleyellow9.setOpaque(true);
		cp.add(circleyellow9);

		circlered1.setBounds(10, 10, 61, 61);
		circlered1.setOpaque(true);
		cp.add(circlered1);
		circlered2.setBounds(80, 10, 61, 61);
		circlered2.setOpaque(true);
		cp.add(circlered2);
		circlered3.setBounds(80, 80, 61, 61);
		circlered3.setOpaque(true);
		cp.add(circlered3);
		circlered4.setBounds(10, 80, 61, 61);
		circlered4.setOpaque(true);
		cp.add(circlered4);
		circlered5.setBounds(38, 366, 61, 61);
		circlered5.setOpaque(true);
		cp.add(circlered5);
		circlered6.setBounds(124, 454, 61, 61);
		circlered6.setOpaque(true);
		cp.add(circlered6);
		circlered7.setBounds(208, 454, 61, 61);
		circlered7.setOpaque(true);
		cp.add(circlered7);
		circlered8.setBounds(292, 454, 61, 61);
		circlered8.setOpaque(true);
		cp.add(circlered8);
		circlered9.setBounds(380, 454, 61, 61);
		circlered9.setOpaque(true);
		cp.add(circlered9);

		jPanel1.setBounds(64, 392, 3, 178);
		jPanel1.setOpaque(true);
		jPanel1.setBackground(Color.BLACK);
		cp.add(jPanel1);
		jPanel2.setBounds(920, 392, 3, 178);
		jPanel2.setOpaque(true);
		jPanel2.setBackground(Color.BLACK);
		cp.add(jPanel2);
		jPanel3.setBounds(408, 64, 178, 3);
		jPanel3.setOpaque(true);
		jPanel3.setBackground(Color.BLACK);
		cp.add(jPanel3);
		jPanel4.setBounds(408, 896, 178, 3);
		jPanel4.setOpaque(true);
		jPanel4.setBackground(Color.BLACK);
		cp.add(jPanel4);
		jPanel5.setBounds(64, 392, 345, 3);
		jPanel5.setOpaque(true);
		jPanel5.setBackground(Color.BLACK);
		cp.add(jPanel5);
		jPanel6.setBounds(408, 64, 3, 330);
		jPanel6.setOpaque(true);
		jPanel6.setBackground(Color.BLACK);
		cp.add(jPanel6);
		jPanel7.setBounds(64, 568, 345, 3);
		jPanel7.setOpaque(true);
		jPanel7.setBackground(Color.BLACK);
		cp.add(jPanel7);
		jPanel8.setBounds(408, 568, 3, 330);
		jPanel8.setOpaque(true);
		jPanel8.setBackground(Color.BLACK);
		cp.add(jPanel8);
		jPanel9.setBounds(584, 568, 3, 330);
		jPanel9.setOpaque(true);
		jPanel9.setBackground(Color.BLACK);
		cp.add(jPanel9);
		jPanel10.setBounds(584, 64, 3, 330);
		jPanel10.setOpaque(true);
		jPanel10.setBackground(Color.BLACK);
		cp.add(jPanel10);
		jPanel11.setBounds(584, 392, 338, 3);
		jPanel11.setOpaque(true);
		jPanel11.setBackground(Color.BLACK);
		cp.add(jPanel11);
		jPanel12.setBounds(584, 568, 338, 3);
		jPanel12.setOpaque(true);
		jPanel12.setBackground(Color.BLACK);
		cp.add(jPanel12);
		setVisible(false);
	}
	
	//getterSetter
	
	public static void onEvent(String s)
	{
		jTextArea1.append(s + "\n");
	}

	public static void onEvent(int i)
	{
		jTextArea1.append(i + "\n");
	}
}
