package gui;
import java.awt.*;
import java.io.PrintStream;

import javax.swing.*;

public class Playground extends JFrame						// JFrame Spielfenster
{
	int r;													// Integer r,g,b Variablen f¸r die Hintergrundfarbe des Fensters
	int g;
	int b;
	private JPanel jPanel1 = new JPanel(null, true);		// JPanels zum zeichen der Linien
	private JPanel jPanel2 = new JPanel(null, true);
	private JPanel jPanel3 = new JPanel(null, true);
	private JPanel jPanel4 = new JPanel(null, true);
	private JPanel jPanel5 = new JPanel(null, true);
	private JPanel jPanel6 = new JPanel(null, true);
	private JPanel jPanel7 = new JPanel(null, true);
	private JPanel jPanel8 = new JPanel(null, true);
	private JPanel jPanel9 = new JPanel(null, true);
	private JPanel jPanel10 = new JPanel(null, true);
	private JPanel jPanel11 = new JPanel(null, true);
	private JPanel jPanel12 = new JPanel(null, true);
	private CircleWhite circleweiﬂ1 = new CircleWhite();
	private CircleWhite circleweiﬂ2 = new CircleWhite();
	private CircleWhite circleweiﬂ3 = new CircleWhite();
	private CircleWhite circleweiﬂ4 = new CircleWhite();
	private CircleWhite circleweiﬂ5 = new CircleWhite();
	private CircleWhite circleweiﬂ6 = new CircleWhite();
	private CircleWhite circleweiﬂ7 = new CircleWhite();
	private CircleWhite circleweiﬂ8 = new CircleWhite();
	private CircleWhite circleweiﬂ9 = new CircleWhite();
	private CircleWhite circleweiﬂ10 = new CircleWhite();
	private CircleWhite circleweiﬂ11 = new CircleWhite();
	private CircleWhite circleweiﬂ12 = new CircleWhite();
	private CircleWhite circleweiﬂ13 = new CircleWhite();
	private CircleWhite circleweiﬂ14 = new CircleWhite();
	private CircleWhite circleweiﬂ15 = new CircleWhite();
	private CircleWhite circleweiﬂ16 = new CircleWhite();
	private CircleWhite circleweiﬂ17 = new CircleWhite();
	private CircleWhite circleweiﬂ18 = new CircleWhite();
	private CircleWhite circleweiﬂ19 = new CircleWhite();
	private CircleWhite circleweiﬂ20 = new CircleWhite();
	private CircleWhite circleweiﬂ21 = new CircleWhite();
	private CircleWhite circleweiﬂ22 = new CircleWhite();
	private CircleWhite circleweiﬂ23 = new CircleWhite();
	private CircleWhite circleweiﬂ24 = new CircleWhite();
	private CircleWhite circleweiﬂ25 = new CircleWhite();
	private CircleWhite circleweiﬂ26 = new CircleWhite();
	private CircleWhite circleweiﬂ27 = new CircleWhite();
	private CircleWhite circleweiﬂ28 = new CircleWhite();
	private CircleWhite circleweiﬂ29 = new CircleWhite();
	private CircleWhite circleweiﬂ30 = new CircleWhite();
	private CircleWhite circleweiﬂ31 = new CircleWhite();
	private CircleWhite circleweiﬂ32 = new CircleWhite();
	private CircleWhite circleweiﬂ33 = new CircleWhite();
	private CircleWhite circleweiﬂ34 = new CircleWhite();
	private CircleWhite circleweiﬂ35 = new CircleWhite();
	private CircleWhite circleweiﬂ36 = new CircleWhite();
	private CircleBlau circleblau1 = new CircleBlau();
	private CircleBlau circleblau2 = new CircleBlau();
	private CircleBlau circleblau3 = new CircleBlau();
	private CircleBlau circleblau4 = new CircleBlau();
	private CircleBlau circleblau5 = new CircleBlau();
	private CircleBlau circleblau6 = new CircleBlau();
	private CircleBlau circleblau7 = new CircleBlau();
	private CircleBlau circleblau8 = new CircleBlau();
	private CircleBlau circleblau9 = new CircleBlau();
	private CircleGreen circlegreen1 = new CircleGreen();
	private CircleGreen circlegreen2 = new CircleGreen();
	private CircleGreen circlegreen3 = new CircleGreen();
	private CircleGreen circlegreen4 = new CircleGreen();
	private CircleGreen circlegreen5 = new CircleGreen();
	private CircleGreen circlegreen6 = new CircleGreen();
	private CircleGreen circlegreen7 = new CircleGreen();
	private CircleGreen circlegreen8 = new CircleGreen();
	private CircleGreen circlegreen9 = new CircleGreen();
	private CircleYellow circleyellow1 = new CircleYellow();
	private CircleYellow circleyellow2 = new CircleYellow();
	private CircleYellow circleyellow3 = new CircleYellow();
	private CircleYellow circleyellow4 = new CircleYellow();
	private CircleYellow circleyellow5 = new CircleYellow();
	private CircleYellow circleyellow6 = new CircleYellow();
	private CircleYellow circleyellow7 = new CircleYellow();
	private CircleYellow circleyellow8 = new CircleYellow();
	private CircleYellow circleyellow9 = new CircleYellow();
	private CircleRed circlered1 = new CircleRed();
	private CircleRed circlered2 = new CircleRed();
	private CircleRed circlered3 = new CircleRed();
	private CircleRed circlered4 = new CircleRed();
	private CircleRed circlered5 = new CircleRed();
	private CircleRed circlered6 = new CircleRed();
	private CircleRed circlered7 = new CircleRed();
	private CircleRed circlered8 = new CircleRed();
	private CircleRed circlered9 = new CircleRed();
	private JLabel textfield1 = new JLabel();
	private JLabel textfield2 = new JLabel();
	private JLabel textfield3 = new JLabel();
	private JLabel textfield4 = new JLabel();
	private static JTextArea jTextArea1 = new JTextArea();
	private JScrollPane jTextArea1ScrollPane = new JScrollPane(jTextArea1);

	
	static void onEvent(String s)
	{
		jTextArea1.append(s + "\n");
	}
	public Playground()
	{
		super();
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);		// Programm wird beim schlieﬂen des Fensters beendet
		int frameWidth = 1800;											// Grˆﬂe des Spielfensters
		int frameHeight = 1000;
		setSize(frameWidth, frameHeight);	
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();		// Fenster wird mittig ausgerichtet
		int x = (d.width - getSize().width) / 2;
		int y = (d.height - getSize().height) / 2;
		setLocation(x, y);
		setTitle("Mensch ‰rgere Dich Nicht");							// Titel des Fensters
		setResizable(false);											// Grˆﬂe nicht ver‰nderbar
		Container cp = getContentPane();								// Container f¸r Fenstervariablen
		cp.setLayout(null);
		cp.setBackground(new Color(r = 204, g = 164, b = 96));			// Hintergrundfarbe Fenster

		jTextArea1ScrollPane.setBounds(980, 10, 795, 940);
		jTextArea1.setFont(new Font("Times New Roman", Font.BOLD, 20));
		cp.add(jTextArea1ScrollPane);
		textfield1.setBounds(150, 20, 100, 30);
	    textfield1.setText(LoadGui.getPlayerOneNameString());
	    cp.add(textfield1); 
	    textfield2.setBounds(740, 20, 100, 30);
	    textfield2.setText(LoadGui.getPlayerTwoNameString());
	    cp.add(textfield2);
	    textfield3.setBounds(150, 830, 100, 30);
	    textfield3.setText(LoadGui.getPlayerThreeNameString());
	    cp.add(textfield3); 
	    textfield4.setBounds(740, 830, 100, 30);
	    textfield4.setText(LoadGui.getPlayerFourNameString());
	    cp.add(textfield4);
		circleweiﬂ1.setBounds(380, 366, 61, 61);						// erstellung der einzelen Bausteine f¸r das Fenster mit Koordinaten
		circleweiﬂ1.setOpaque(true);
		cp.add(circleweiﬂ1);
		circleweiﬂ2.setBounds(380, 284, 61, 61);
		circleweiﬂ2.setOpaque(true);
		cp.add(circleweiﬂ2);
		circleweiﬂ3.setBounds(380, 202, 61, 61);
		circleweiﬂ3.setOpaque(true);
		cp.add(circleweiﬂ3);
		circleweiﬂ4.setBounds(380, 120, 61, 61);
		circleweiﬂ4.setOpaque(true);
		cp.add(circleweiﬂ4);
		circleweiﬂ5.setBounds(380, 38, 61, 61);
		circleweiﬂ5.setOpaque(true);
		cp.add(circleweiﬂ5);
		circleweiﬂ6.setBounds(467, 38, 61, 61);
		circleweiﬂ6.setOpaque(true);
		cp.add(circleweiﬂ6);
		circleweiﬂ7.setBounds(555, 120, 61, 61);
		circleweiﬂ7.setOpaque(true);
		cp.add(circleweiﬂ7);
		circleweiﬂ8.setBounds(555, 202, 61, 61);
		circleweiﬂ8.setOpaque(true);
		cp.add(circleweiﬂ8);
		circleweiﬂ9.setBounds(555, 284, 61, 61);
		circleweiﬂ9.setOpaque(true);
		cp.add(circleweiﬂ9);
		circleweiﬂ10.setBounds(555, 366, 61, 61);
		circleweiﬂ10.setOpaque(true);
		cp.add(circleweiﬂ10);
		circleweiﬂ11.setBounds(642, 366, 61, 61);
		circleweiﬂ11.setOpaque(true);
		cp.add(circleweiﬂ11);
		circleweiﬂ12.setBounds(724, 366, 61, 61);
		circleweiﬂ12.setOpaque(true);
		cp.add(circleweiﬂ12);
		circleweiﬂ13.setBounds(806, 366, 61, 61);
		circleweiﬂ13.setOpaque(true);
		cp.add(circleweiﬂ13);
		circleweiﬂ14.setBounds(888, 366, 61, 61);
		circleweiﬂ14.setOpaque(true);
		cp.add(circleweiﬂ14);
		circleweiﬂ15.setBounds(888, 454, 61, 61);
		circleweiﬂ15.setOpaque(true);
		cp.add(circleweiﬂ15);
		circleweiﬂ16.setBounds(806, 542, 61, 61);
		circleweiﬂ16.setOpaque(true);
		cp.add(circleweiﬂ16);
		circleweiﬂ17.setBounds(724, 542, 61, 61);
		circleweiﬂ17.setOpaque(true);
		cp.add(circleweiﬂ17);
		circleweiﬂ18.setBounds(642, 542, 61, 61);
		circleweiﬂ18.setOpaque(true);
		cp.add(circleweiﬂ18);
		circleweiﬂ19.setBounds(555, 542, 61, 61);
		circleweiﬂ19.setOpaque(true);
		cp.add(circleweiﬂ19);
		circleweiﬂ20.setBounds(555, 624, 61, 61);
		circleweiﬂ20.setOpaque(true);
		cp.add(circleweiﬂ20);
		circleweiﬂ21.setBounds(555, 706, 61, 61);
		circleweiﬂ21.setOpaque(true);
		cp.add(circleweiﬂ21);
		circleweiﬂ22.setBounds(555, 788, 61, 61);
		circleweiﬂ22.setOpaque(true);
		cp.add(circleweiﬂ22);
		circleweiﬂ23.setBounds(555, 870, 61, 61);
		circleweiﬂ23.setOpaque(true);
		cp.add(circleweiﬂ23);
		circleweiﬂ24.setBounds(467, 870, 61, 61);
		circleweiﬂ24.setOpaque(true);
		cp.add(circleweiﬂ24);
		circleweiﬂ25.setBounds(380, 788, 61, 61);
		circleweiﬂ25.setOpaque(true);
		cp.add(circleweiﬂ25);
		circleweiﬂ26.setBounds(380, 706, 61, 61);
		circleweiﬂ26.setOpaque(true);
		cp.add(circleweiﬂ26);
		circleweiﬂ27.setBounds(380, 624, 61, 61);
		circleweiﬂ27.setOpaque(true);
		cp.add(circleweiﬂ27);
		circleweiﬂ28.setBounds(380, 542, 61, 61);
		circleweiﬂ28.setOpaque(true);
		cp.add(circleweiﬂ28);
		circleweiﬂ29.setBounds(293, 542, 61, 61);
		circleweiﬂ29.setOpaque(true);
		cp.add(circleweiﬂ29);
		circleweiﬂ30.setBounds(211, 542, 61, 61);
		circleweiﬂ30.setOpaque(true);
		cp.add(circleweiﬂ30);
		circleweiﬂ31.setBounds(126, 542, 61, 61);
		circleweiﬂ31.setOpaque(true);
		cp.add(circleweiﬂ31);
		circleweiﬂ32.setBounds(38, 542, 61, 61);
		circleweiﬂ32.setOpaque(true);
		cp.add(circleweiﬂ32);
		circleweiﬂ33.setBounds(38, 454, 61, 61);
		circleweiﬂ33.setOpaque(true);
		cp.add(circleweiﬂ33);
		circleweiﬂ34.setBounds(124, 366, 61, 61);
		circleweiﬂ34.setOpaque(true);
		cp.add(circleweiﬂ34);
		circleweiﬂ35.setBounds(208, 366, 61, 61);
		circleweiﬂ35.setOpaque(true);
		cp.add(circleweiﬂ35);
		circleweiﬂ36.setBounds(292, 366, 61, 61);
		circleweiﬂ36.setOpaque(true);
		cp.add(circleweiﬂ36);

		circlegreen1.setBounds(888, 542, 61, 61);
		circlegreen1.setOpaque(true);
		cp.add(circlegreen1);
		circlegreen2.setBounds(806, 454, 61, 61);
		circlegreen2.setOpaque(true);
		cp.add(circlegreen2);
		circlegreen3.setBounds(724, 454, 61, 61);
		circlegreen3.setOpaque(true);
		cp.add(circlegreen3);
		circlegreen4.setBounds(642, 454, 61, 61);
		circlegreen4.setOpaque(true);
		cp.add(circlegreen4);
		circlegreen5.setBounds(555, 454, 61, 61);
		circlegreen5.setOpaque(true);
		cp.add(circlegreen5);
		circlegreen6.setBounds(910, 890, 61, 61);
		circlegreen6.setOpaque(true);
		cp.add(circlegreen6);
		circlegreen7.setBounds(910, 820, 61, 61);
		circlegreen7.setOpaque(true);
		cp.add(circlegreen7);
		circlegreen8.setBounds(840, 820, 61, 61);
		circlegreen8.setOpaque(true);
		cp.add(circlegreen8);
		circlegreen9.setBounds(840, 890, 61, 61);
		circlegreen9.setOpaque(true);
		cp.add(circlegreen9);

		circleblau1.setBounds(555, 38, 61, 61);
		circleblau1.setOpaque(true);
		cp.add(circleblau1);
		circleblau2.setBounds(910, 10, 61, 61);
		circleblau2.setOpaque(true);
		cp.add(circleblau2);
		circleblau3.setBounds(840, 10, 61, 61);
		circleblau3.setOpaque(true);
		cp.add(circleblau3);
		circleblau4.setBounds(910, 80, 61, 61);
		circleblau4.setOpaque(true);
		cp.add(circleblau4);
		circleblau5.setBounds(840, 80, 61, 61);
		circleblau5.setOpaque(true);
		cp.add(circleblau5);
		circleblau6.setBounds(467, 120, 61, 61);
		circleblau6.setOpaque(true);
		cp.add(circleblau6);
		circleblau7.setBounds(467, 202, 61, 61);
		circleblau7.setOpaque(true);
		cp.add(circleblau7);
		circleblau8.setBounds(467, 284, 61, 61);
		circleblau8.setOpaque(true);
		cp.add(circleblau8);
		circleblau9.setBounds(467, 366, 61, 61);
		circleblau9.setOpaque(true);
		cp.add(circleblau9);

		circleyellow1.setBounds(467, 788, 61, 61);
		circleyellow1.setOpaque(true);
		cp.add(circleyellow1);
		circleyellow2.setBounds(467, 706, 61, 61);
		circleyellow2.setOpaque(true);
		cp.add(circleyellow2);
		circleyellow3.setBounds(467, 624, 61, 61);
		circleyellow3.setOpaque(true);
		cp.add(circleyellow3);
		circleyellow4.setBounds(467, 542, 61, 61);
		circleyellow4.setOpaque(true);
		cp.add(circleyellow4);
		circleyellow5.setBounds(380, 870, 61, 61);
		circleyellow5.setOpaque(true);
		cp.add(circleyellow5);
		circleyellow6.setBounds(80, 890, 61, 61);
		circleyellow6.setOpaque(true);
		cp.add(circleyellow6);
		circleyellow7.setBounds(10, 890, 61, 61);
		circleyellow7.setOpaque(true);
		cp.add(circleyellow7);
		circleyellow8.setBounds(10, 820, 61, 61);
		circleyellow8.setOpaque(true);
		cp.add(circleyellow8);
		circleyellow9.setBounds(80, 820, 61, 61);
		circleyellow9.setOpaque(true);
		cp.add(circleyellow9);

		circlered1.setBounds(10, 10, 61, 61);
		circlered1.setOpaque(true);
		cp.add(circlered1);
		circlered2.setBounds(80, 10, 61, 61);
		circlered2.setOpaque(true);
		cp.add(circlered2);
		circlered3.setBounds(80, 80, 61, 61);
		circlered3.setOpaque(true);
		cp.add(circlered3);
		circlered4.setBounds(10, 80, 61, 61);
		circlered4.setOpaque(true);
		cp.add(circlered4);
		circlered5.setBounds(38, 366, 61, 61);
		circlered5.setOpaque(true);
		cp.add(circlered5);
		circlered6.setBounds(124, 454, 61, 61);
		circlered6.setOpaque(true);
		cp.add(circlered6);
		circlered7.setBounds(208, 454, 61, 61);
		circlered7.setOpaque(true);
		cp.add(circlered7);
		circlered8.setBounds(292, 454, 61, 61);
		circlered8.setOpaque(true);
		cp.add(circlered8);
		circlered9.setBounds(380, 454, 61, 61);
		circlered9.setOpaque(true);
		cp.add(circlered9);

		jPanel1.setBounds(64, 392, 3, 178);
		jPanel1.setOpaque(true);
		jPanel1.setBackground(Color.BLACK);
		cp.add(jPanel1);
		jPanel2.setBounds(920, 392, 3, 178);
		jPanel2.setOpaque(true);
		jPanel2.setBackground(Color.BLACK);
		cp.add(jPanel2);
		jPanel3.setBounds(408, 64, 178, 3);
		jPanel3.setOpaque(true);
		jPanel3.setBackground(Color.BLACK);
		cp.add(jPanel3);
		jPanel4.setBounds(408, 896, 178, 3);
		jPanel4.setOpaque(true);
		jPanel4.setBackground(Color.BLACK);
		cp.add(jPanel4);
		jPanel5.setBounds(64, 392, 345, 3);
		jPanel5.setOpaque(true);
		jPanel5.setBackground(Color.BLACK);
		cp.add(jPanel5);
		jPanel6.setBounds(408, 64, 3, 330);
		jPanel6.setOpaque(true);
		jPanel6.setBackground(Color.BLACK);
		cp.add(jPanel6);
		jPanel7.setBounds(64, 568, 345, 3);
		jPanel7.setOpaque(true);
		jPanel7.setBackground(Color.BLACK);
		cp.add(jPanel7);
		jPanel8.setBounds(408, 568, 3, 330);
		jPanel8.setOpaque(true);
		jPanel8.setBackground(Color.BLACK);
		cp.add(jPanel8);
		jPanel9.setBounds(584, 568, 3, 330);
		jPanel9.setOpaque(true);
		jPanel9.setBackground(Color.BLACK);
		cp.add(jPanel9);
		jPanel10.setBounds(584, 64, 3, 330);
		jPanel10.setOpaque(true);
		jPanel10.setBackground(Color.BLACK);
		cp.add(jPanel10);
		jPanel11.setBounds(584, 392, 338, 3);
		jPanel11.setOpaque(true);
		jPanel11.setBackground(Color.BLACK);
		cp.add(jPanel11);
		jPanel12.setBounds(584, 568, 338, 3);
		jPanel12.setOpaque(true);
		jPanel12.setBackground(Color.BLACK);
		cp.add(jPanel12);
		setVisible(true);
	}
}
